spring:
  profiles:
    active: dev,swagger
  application:
    name: PragraLMS
  web:
    resources:
      static-locations: classpath:templates/static

git:
  api:
    user: https://api.github.com/users/{login}
